
require "basis"
--GENERATED PERMUTATIONS OF CL4,1 ON A NULL BASIS (Selected using a geometrical heuristic)
--FILE GENERATED BY BUILD.LUA
--total number of built types: 129

--total number of all types: 44
Rot = { id = "Rot", desc = "Rotor", bases = {_s, _e12, _e13, _e23, }, key = 105 }
Mot = { id = "Mot", desc = "Motor", bases = {_s, _e12, _e13, _e23, _e1ni, _e2ni, _e3ni, _e123ni, }, key = 9830505 }
Dil = { id = "Dil", desc = "Dilator", bases = {_s, _noni, }, key = 16777217 }
Trv = { id = "Trv", desc = "Transversor", bases = {_s, _e1no, _e2no, _e3no, }, key = 5633 }
Mtd = { id = "Mtd", desc = "Motor Dilator", bases = {_s, _e12, _e13, _e23, _e1ni, _e2ni, _e3ni, _noni, _e12noni, _e13noni, _e23noni, _e123ni, }, key = 1771438185 }
Trs = { id = "Trs", desc = "Translator", bases = {_s, _e1ni, _e2ni, _e3ni, }, key = 1441793 }
Rtc = { id = "Rtc", desc = "Rotor Circle", bases = {_e1, _e2, _e3, _no, _ni, _e12no, _e13no, _e23no, _e12ni, _e13ni, _e23ni, _e1noni, _e2noni, _e3noni, _e123, _e123noni, }, key = -1771476586 }
Mtt = { id = "Mtt", desc = "Motor Transversor", bases = {_s, _e12, _e13, _e23, _e1no, _e2no, _e3no, _e1ni, _e2ni, _e3ni, _noni, _e12noni, _e13noni, _e23noni, _e123no, _e123ni, }, key = 1771476585 }
Rtt = { id = "Rtt", desc = "Rotor Transveror", bases = {_s, _e12, _e13, _e23, _e1no, _e2no, _e3no, _e123no, }, key = 38505 }
Rtd = { id = "Rtd", desc = "Rotor Dilator", bases = {_s, _e12, _e13, _e23, _noni, _e12noni, _e13noni, _e23noni, }, key = 1761607785 }
Tvd = { id = "Tvd", desc = "Transversor Dilator", bases = {_s, _e1no, _e2no, _e3no, _noni, }, key = 16782849 }
Tsd = { id = "Tsd", desc = "Translator Dilator", bases = {_s, _e1ni, _e2ni, _e3ni, _noni, }, key = 18219009 }
Trt = { id = "Trt", desc = "Transversor Translator", bases = {_s, _e12, _e13, _e23, _e1no, _e2no, _e3no, _e1ni, _e2ni, _e3ni, _noni, _e12noni, _e13noni, _e23noni, }, key = 1763055209 }
Rvd = { id = "Rvd", desc = "Rotor Transversor Dilator", bases = {_s, _e12, _e13, _e23, _e1no, _e2no, _e3no, _noni, _e12noni, _e13noni, _e23noni, _e123no, }, key = 1761646185 }
Tst = { id = "Tst", desc = "Transv Transv Transl", bases = {_s, _e12, _e13, _e23, _e1no, _e2no, _e3no, _e1ni, _e2ni, _e3ni, _noni, _e12noni, _e13noni, _e23noni, _e123no, }, key = 1763087977 }
Tvt = { id = "Tvt", desc = "Trans Transv Transl", bases = {_s, _e12, _e13, _e23, _e1no, _e2no, _e3no, _e1ni, _e2ni, _e3ni, _noni, _e12noni, _e13noni, _e23noni, _e123ni, }, key = 1771443817 }
Bst = { id = "Bst", desc = "Booster", bases = {_s, _e12, _e13, _e23, _e1no, _e2no, _e3no, _e1ni, _e2ni, _e3ni, _noni, }, key = 18224745 }
Sca = { id = "Sca", desc = "Scalar", bases = {_s, }, key = 1 }
Ori = { id = "Ori", desc = "Origin", bases = {_no, }, key = 256 }
Inf = { id = "Inf", desc = "Infinity", bases = {_ni, }, key = 65536 }
Mnk = { id = "Mnk", desc = "Minkowski Plane", bases = {_noni, }, key = 16777216 }
Hyp = { id = "Hyp", desc = "Imaginary Sphere", bases = {_no, _ni, }, key = 65792 }
Pss = { id = "Pss", desc = "Pseudoscalar", bases = {_e123noni, }, key = -2147483648 }
Pnt = { id = "Pnt", desc = "Point", bases = {_e1, _e2, _e3, _no, _ni, }, key = 65814 }
Par = { id = "Par", desc = "Point Pair", bases = {_e12, _e13, _e23, _e1no, _e2no, _e3no, _e1ni, _e2ni, _e3ni, _noni, }, key = 18224744 }
Cir = { id = "Cir", desc = "Circle", bases = {_e12no, _e13no, _e23no, _e12ni, _e13ni, _e23ni, _e1noni, _e2noni, _e3noni, _e123, }, key = 375941248 }
Sph = { id = "Sph", desc = "Sphere", bases = {_e12noni, _e13noni, _e23noni, _e123no, _e123ni, }, key = 1753251840 }
Sta = { id = "Sta", desc = "Space Time Wedge", bases = {_e12, _e13, _e23, _e1no, _e2no, _e3no, _e1ni, _e2ni, _e3ni, }, key = 1447528 }
Drv = { id = "Drv", desc = "Direction Vector", bases = {_e1ni, _e2ni, _e3ni, }, key = 1441792 }
Drb = { id = "Drb", desc = "Direction Bivector", bases = {_e12ni, _e13ni, _e23ni, }, key = 6815744 }
Drt = { id = "Drt", desc = "Direction Trivector", bases = {_e123ni, }, key = 8388608 }
Tnv = { id = "Tnv", desc = "Tangent Vector at Origin", bases = {_e1no, _e2no, _e3no, }, key = 5632 }
Tnb = { id = "Tnb", desc = "Tangent Bivector at Origin", bases = {_e12no, _e13no, _e23no, }, key = 26624 }
Tnt = { id = "Tnt", desc = "Tangent Trivector at Origin", bases = {_e123no, }, key = 32768 }
Lin = { id = "Lin", desc = "Line", bases = {_e12ni, _e13ni, _e23ni, _e1noni, _e2noni, _e3noni, }, key = 375914496 }
Pln = { id = "Pln", desc = "Plane", bases = {_e12noni, _e13noni, _e23noni, _e123ni, }, key = 1753219072 }
Flp = { id = "Flp", desc = "Flat Point", bases = {_e1ni, _e2ni, _e3ni, _noni, }, key = 18219008 }
Dfp = { id = "Dfp", desc = "Dual Flat Point", bases = {_e12ni, _e13ni, _e23ni, _e123, }, key = 6815872 }
Dll = { id = "Dll", desc = "Dual Line", bases = {_e12, _e13, _e23, _e1ni, _e2ni, _e3ni, }, key = 1441896 }
Dlp = { id = "Dlp", desc = "Dual Plane", bases = {_e1, _e2, _e3, _ni, }, key = 65558 }
Vec = { id = "Vec", desc = "Vector", bases = {_e1, _e2, _e3, }, key = 22 }
Biv = { id = "Biv", desc = "Bivector", bases = {_e12, _e13, _e23, }, key = 104 }
Tri = { id = "Tri", desc = "Trivector", bases = {_e123, }, key = 128 }
Gld = { id = "Gld", desc = "Glide", bases = {_e1, _e2, _e3, _ni, _e12ni, _e13ni, _e23ni, }, key = 6881302 }
Rot_Ori = { id = "Rot_Ori", desc = "Rotor Origin", bases = {_no, _e12no, _e13no, _e23no, }, key = 26880 }
Rot_Inf = { id = "Rot_Inf", desc = "Rotor Infinity", bases = {_ni, _e12ni, _e13ni, _e23ni, }, key = 6881280 }
Rot_Mnk = { id = "Rot_Mnk", desc = "Rotor Minkowski Plane", bases = {_noni, _e12noni, _e13noni, _e23noni, }, key = 1761607680 }
Rot_Hyp = { id = "Rot_Hyp", desc = "Rotor Imaginary Sphere", bases = {_no, _ni, _e12no, _e13no, _e23no, _e12ni, _e13ni, _e23ni, }, key = 6908160 }
Rot_Pss = { id = "Rot_Pss", desc = "Rotor Pseudoscalar", bases = {_e1noni, _e2noni, _e3noni, _e123noni, }, key = -1778384896 }
Rot_Pnt = { id = "Rot_Pnt", desc = "Rotor Point", bases = {_e1, _e2, _e3, _no, _ni, _e12no, _e13no, _e23no, _e12ni, _e13ni, _e23ni, _e123, }, key = 6908310 }
Rot_Sph = { id = "Rot_Sph", desc = "Rotor Sphere", bases = {_e1no, _e2no, _e3no, _e1ni, _e2ni, _e3ni, _noni, _e12noni, _e13noni, _e23noni, _e123no, _e123ni, }, key = 1771476480 }
Rot_Sta = { id = "Rot_Sta", desc = "Rotor Space Time Wedge", bases = {_s, _e12, _e13, _e23, _e1no, _e2no, _e3no, _e1ni, _e2ni, _e3ni, _e123no, _e123ni, }, key = 9868905 }
Rot_Drv = { id = "Rot_Drv", desc = "Rotor Direction Vector", bases = {_e1ni, _e2ni, _e3ni, _e123ni, }, key = 9830400 }
Rot_Tnv = { id = "Rot_Tnv", desc = "Rotor Tangent Vector at Origin", bases = {_e1no, _e2no, _e3no, _e123no, }, key = 38400 }
Rot_Lin = { id = "Rot_Lin", desc = "Rotor Line", bases = {_ni, _e12ni, _e13ni, _e23ni, _e1noni, _e2noni, _e3noni, _e123noni, }, key = -1771503616 }
Rot_Pln = { id = "Rot_Pln", desc = "Rotor Plane", bases = {_e1ni, _e2ni, _e3ni, _noni, _e12noni, _e13noni, _e23noni, _e123ni, }, key = 1771438080 }
Rot_Dfp = { id = "Rot_Dfp", desc = "Rotor Dual Flat Point", bases = {_e1, _e2, _e3, _ni, _e12ni, _e13ni, _e23ni, _e123, }, key = 6881430 }
Rot_Vec = { id = "Rot_Vec", desc = "Rotor Vector", bases = {_e1, _e2, _e3, _e123, }, key = 150 }
Mot_Ori = { id = "Mot_Ori", desc = "Motor Origin", bases = {_e1, _e2, _e3, _no, _e12no, _e13no, _e23no, _e1noni, _e2noni, _e3noni, _e123, _e123noni, }, key = -1778357866 }
Dil_Pss = { id = "Dil_Pss", desc = "Dilator Pseudoscalar", bases = {_e123, _e123noni, }, key = -2147483520 }
Dil_Pnt = { id = "Dil_Pnt", desc = "Dilator Point", bases = {_e1, _e2, _e3, _no, _ni, _e1noni, _e2noni, _e3noni, }, key = 369164566 }
Dil_Cir = { id = "Dil_Cir", desc = "Dilator Circle", bases = {_e1, _e2, _e3, _e12no, _e13no, _e23no, _e12ni, _e13ni, _e23ni, _e1noni, _e2noni, _e3noni, _e123, _e123noni, }, key = -1771542378 }
Dil_Sph = { id = "Dil_Sph", desc = "Dilator Sphere", bases = {_e12, _e13, _e23, _e12noni, _e13noni, _e23noni, _e123no, _e123ni, }, key = 1753251944 }
Dil_Sta = { id = "Dil_Sta", desc = "Dilator Space Time Wedge", bases = {_e12, _e13, _e23, _e1no, _e2no, _e3no, _e1ni, _e2ni, _e3ni, _e12noni, _e13noni, _e23noni, }, key = 1746277992 }
Dil_Lin = { id = "Dil_Lin", desc = "Dilator Line", bases = {_e1, _e2, _e3, _e12ni, _e13ni, _e23ni, _e1noni, _e2noni, _e3noni, }, key = 375914518 }
Dil_Pln = { id = "Dil_Pln", desc = "Dilator Plane", bases = {_e12, _e13, _e23, _e12noni, _e13noni, _e23noni, _e123ni, }, key = 1753219176 }
Dil_Dfp = { id = "Dil_Dfp", desc = "Dilator Dual Flat Point", bases = {_e12ni, _e13ni, _e23ni, _e123, _e123noni, }, key = -2140667776 }
Dil_Dll = { id = "Dil_Dll", desc = "Dilator Dual Line", bases = {_e12, _e13, _e23, _e1ni, _e2ni, _e3ni, _e12noni, _e13noni, _e23noni, }, key = 1746272360 }
Dil_Dlp = { id = "Dil_Dlp", desc = "Dilator Dual Plane", bases = {_e1, _e2, _e3, _ni, _e1noni, _e2noni, _e3noni, }, key = 369164310 }
Dil_Vec = { id = "Dil_Vec", desc = "Dilator Vector", bases = {_e1, _e2, _e3, _e1noni, _e2noni, _e3noni, }, key = 369098774 }
Dil_Biv = { id = "Dil_Biv", desc = "Dilator Bivector", bases = {_e12, _e13, _e23, _e12noni, _e13noni, _e23noni, }, key = 1744830568 }
Dil_Gld = { id = "Dil_Gld", desc = "Dilator Glide", bases = {_e1, _e2, _e3, _ni, _e12ni, _e13ni, _e23ni, _e1noni, _e2noni, _e3noni, }, key = 375980054 }
Trv_Mnk = { id = "Trv_Mnk", desc = "Transversor Minkowski Plane", bases = {_e1no, _e2no, _e3no, _noni, }, key = 16782848 }
Trv_Pss = { id = "Trv_Pss", desc = "Transversor Pseudoscalar", bases = {_e12no, _e13no, _e23no, _e123noni, }, key = -2147457024 }
Trv_Pnt = { id = "Trv_Pnt", desc = "Transversor Point", bases = {_e1, _e2, _e3, _no, _ni, _e12no, _e13no, _e23no, _e1noni, _e2noni, _e3noni, }, key = 369191190 }
Trv_Cir = { id = "Trv_Cir", desc = "Transversor Circle", bases = {_e1, _e2, _e3, _no, _e12no, _e13no, _e23no, _e12ni, _e13ni, _e23ni, _e1noni, _e2noni, _e3noni, _e123, _e123noni, }, key = -1771542122 }
Trv_Sph = { id = "Trv_Sph", desc = "Transversor Sphere", bases = {_e12, _e13, _e23, _e1no, _e2no, _e3no, _e12noni, _e13noni, _e23noni, _e123no, _e123ni, }, key = 1753257576 }
Trv_Drv = { id = "Trv_Drv", desc = "Transversor Direction Vector", bases = {_s, _e12, _e13, _e23, _e1ni, _e2ni, _e3ni, _noni, _e12noni, _e13noni, _e23noni, }, key = 1763049577 }
Trv_Drb = { id = "Trv_Drb", desc = "Transversor Direction Bivector", bases = {_e1, _e2, _e3, _e12ni, _e13ni, _e23ni, _e1noni, _e2noni, _e3noni, _e123, _e123noni, }, key = -1771569002 }
Trv_Vec = { id = "Trv_Vec", desc = "Transversor Vector", bases = {_e1, _e2, _e3, _no, _e12no, _e13no, _e23no, }, key = 26902 }
Trv_Biv = { id = "Trv_Biv", desc = "Transversor Bivector", bases = {_e12, _e13, _e23, _e1no, _e2no, _e3no, _e123no, }, key = 38504 }
Trv_Tri = { id = "Trv_Tri", desc = "Transversor Trivector", bases = {_e12no, _e13no, _e23no, _e123, }, key = 26752 }
Mtd_Pss = { id = "Mtd_Pss", desc = "Motor Dilator Pseudoscalar", bases = {_e1, _e2, _e3, _ni, _e12ni, _e13ni, _e23ni, _e1noni, _e2noni, _e3noni, _e123, _e123noni, }, key = -1771503466 }
Trs_Ori = { id = "Trs_Ori", desc = "Translator Origin", bases = {_e1, _e2, _e3, _no, _e1noni, _e2noni, _e3noni, }, key = 369099030 }
Trs_Pss = { id = "Trs_Pss", desc = "Translator Pseudoscalar", bases = {_e12ni, _e13ni, _e23ni, _e123noni, }, key = -2140667904 }
Trs_Pnt = { id = "Trs_Pnt", desc = "Translator Point", bases = {_e1, _e2, _e3, _no, _ni, _e12ni, _e13ni, _e23ni, _e1noni, _e2noni, _e3noni, }, key = 375980310 }
Trs_Cir = { id = "Trs_Cir", desc = "Translator Circle", bases = {_e1, _e2, _e3, _ni, _e12no, _e13no, _e23no, _e12ni, _e13ni, _e23ni, _e1noni, _e2noni, _e3noni, _e123, _e123noni, }, key = -1771476842 }
Trs_Sph = { id = "Trs_Sph", desc = "Translator Sphere", bases = {_e12, _e13, _e23, _e1ni, _e2ni, _e3ni, _e12noni, _e13noni, _e23noni, _e123no, _e123ni, }, key = 1754693736 }
Trs_Tnv = { id = "Trs_Tnv", desc = "Translator Tangent Vector at Origin", bases = {_s, _e12, _e13, _e23, _e1no, _e2no, _e3no, _noni, _e12noni, _e13noni, _e23noni, }, key = 1761613417 }
Trs_Tnb = { id = "Trs_Tnb", desc = "Translator Tangent Bivector at Origin", bases = {_e1, _e2, _e3, _e12no, _e13no, _e23no, _e1noni, _e2noni, _e3noni, _e123, _e123noni, }, key = -1778358122 }
Trs_Tnt = { id = "Trs_Tnt", desc = "Translator Tangent Trivector at Origin", bases = {_e12, _e13, _e23, _e12noni, _e13noni, _e23noni, _e123no, }, key = 1744863336 }
Trs_Lin = { id = "Trs_Lin", desc = "Translator Line", bases = {_ni, _e12ni, _e13ni, _e23ni, _e1noni, _e2noni, _e3noni, }, key = 375980032 }
Trs_Pln = { id = "Trs_Pln", desc = "Translator Plane", bases = {_e1ni, _e2ni, _e3ni, _e12noni, _e13noni, _e23noni, _e123ni, }, key = 1754660864 }
Trs_Dll = { id = "Trs_Dll", desc = "Translator Dual Line", bases = {_e12, _e13, _e23, _e1ni, _e2ni, _e3ni, _e123ni, }, key = 9830504 }
Rtt_Mnk = { id = "Rtt_Mnk", desc = "Rotor Transveror Minkowski Plane", bases = {_e1no, _e2no, _e3no, _noni, _e12noni, _e13noni, _e23noni, _e123no, }, key = 1761646080 }
Rtt_Pss = { id = "Rtt_Pss", desc = "Rotor Transveror Pseudoscalar", bases = {_no, _e12no, _e13no, _e23no, _e1noni, _e2noni, _e3noni, _e123noni, }, key = -1778358016 }
Rtt_Vec = { id = "Rtt_Vec", desc = "Rotor Transveror Vector", bases = {_e1, _e2, _e3, _no, _e12no, _e13no, _e23no, _e123, }, key = 27030 }
Rtd_Pss = { id = "Rtd_Pss", desc = "Rotor Dilator Pseudoscalar", bases = {_e1, _e2, _e3, _e1noni, _e2noni, _e3noni, _e123, _e123noni, }, key = -1778384746 }
Tvd_Pss = { id = "Tvd_Pss", desc = "Transversor Dilator Pseudoscalar", bases = {_e12no, _e13no, _e23no, _e123, _e123noni, }, key = -2147456896 }
Tvd_Vec = { id = "Tvd_Vec", desc = "Transversor Dilator Vector", bases = {_e1, _e2, _e3, _no, _e12no, _e13no, _e23no, _e1noni, _e2noni, _e3noni, }, key = 369125654 }
Tvd_Biv = { id = "Tvd_Biv", desc = "Transversor Dilator Bivector", bases = {_e12, _e13, _e23, _e1no, _e2no, _e3no, _e12noni, _e13noni, _e23noni, _e123no, }, key = 1744868968 }
Tsd_Pln = { id = "Tsd_Pln", desc = "Translator Dilator Plane", bases = {_e12, _e13, _e23, _e1ni, _e2ni, _e3ni, _e12noni, _e13noni, _e23noni, _e123ni, }, key = 1754660968 }
Trt_Hyp = { id = "Trt_Hyp", desc = "Transversor Translator Imaginary Sphere", bases = {_e1, _e2, _e3, _no, _ni, _e12no, _e13no, _e23no, _e12ni, _e13ni, _e23ni, _e1noni, _e2noni, _e3noni, }, key = 376006934 }
Bst_Mnk = { id = "Bst_Mnk", desc = "Booster Minkowski Plane", bases = {_s, _e1no, _e2no, _e3no, _e1ni, _e2ni, _e3ni, _noni, _e12noni, _e13noni, _e23noni, }, key = 1763055105 }
Bst_Pss = { id = "Bst_Pss", desc = "Booster Pseudoscalar", bases = {_e12no, _e13no, _e23no, _e12ni, _e13ni, _e23ni, _e1noni, _e2noni, _e3noni, _e123, _e123noni, }, key = -1771542400 }
Bst_Pnt = { id = "Bst_Pnt", desc = "Booster Point", bases = {_e1, _e2, _e3, _no, _ni, _e12no, _e13no, _e23no, _e12ni, _e13ni, _e23ni, _e1noni, _e2noni, _e3noni, _e123, }, key = 376007062 }
Bst_Sph = { id = "Bst_Sph", desc = "Booster Sphere", bases = {_e12, _e13, _e23, _e1no, _e2no, _e3no, _e1ni, _e2ni, _e3ni, _noni, _e12noni, _e13noni, _e23noni, _e123no, _e123ni, }, key = 1771476584 }
Bst_Biv = { id = "Bst_Biv", desc = "Booster Bivector", bases = {_s, _e12, _e13, _e23, _e1no, _e2no, _e3no, _e1ni, _e2ni, _e3ni, _e12noni, _e13noni, _e23noni, _e123no, _e123ni, }, key = 1754699369 }
Bst_Tri = { id = "Bst_Tri", desc = "Booster Trivector", bases = {_e1, _e2, _e3, _e12no, _e13no, _e23no, _e12ni, _e13ni, _e23ni, _e123, _e123noni, }, key = -2140641130 }
Ori_Ori = { id = "Ori_Ori", desc = "Origin Origin", bases = {}, key = 0 }
Ori_Sta = { id = "Ori_Sta", desc = "Origin Space Time Wedge", bases = {_e1, _e2, _e3, _e12no, _e13no, _e23no, _e1noni, _e2noni, _e3noni, }, key = 369125398 }
Ori_Lin = { id = "Ori_Lin", desc = "Origin Line", bases = {_e12, _e13, _e23, _e1no, _e2no, _e3no, _e12noni, _e13noni, _e23noni, }, key = 1744836200 }
Mnk_Pnt = { id = "Mnk_Pnt", desc = "Minkowski Plane Point", bases = {_no, _ni, _e1noni, _e2noni, _e3noni, }, key = 369164544 }
Mnk_Par = { id = "Mnk_Par", desc = "Minkowski Plane Point Pair", bases = {_s, _e1no, _e2no, _e3no, _e1ni, _e2ni, _e3ni, _e12noni, _e13noni, _e23noni, }, key = 1746277889 }
Mnk_Cir = { id = "Mnk_Cir", desc = "Minkowski Plane Circle", bases = {_e1, _e2, _e3, _e12no, _e13no, _e23no, _e12ni, _e13ni, _e23ni, _e123noni, }, key = -2140641258 }
Mnk_Sph = { id = "Mnk_Sph", desc = "Minkowski Plane Sphere", bases = {_e12, _e13, _e23, _e123no, _e123ni, }, key = 8421480 }
Mnk_Sta = { id = "Mnk_Sta", desc = "Minkowski Plane Space Time Wedge", bases = {_e1no, _e2no, _e3no, _e1ni, _e2ni, _e3ni, _e12noni, _e13noni, _e23noni, }, key = 1746277888 }
Mnk_Lin = { id = "Mnk_Lin", desc = "Minkowski Plane Line", bases = {_e1, _e2, _e3, _e12ni, _e13ni, _e23ni, }, key = 6815766 }
Mnk_Pln = { id = "Mnk_Pln", desc = "Minkowski Plane Plane", bases = {_e12, _e13, _e23, _e123ni, }, key = 8388712 }
Mnk_Dll = { id = "Mnk_Dll", desc = "Minkowski Plane Dual Line", bases = {_e1ni, _e2ni, _e3ni, _e12noni, _e13noni, _e23noni, }, key = 1746272256 }
Mnk_Dlp = { id = "Mnk_Dlp", desc = "Minkowski Plane Dual Plane", bases = {_ni, _e1noni, _e2noni, _e3noni, }, key = 369164288 }
Mnk_Vec = { id = "Mnk_Vec", desc = "Minkowski Plane Vector", bases = {_e1noni, _e2noni, _e3noni, }, key = 369098752 }
Mnk_Biv = { id = "Mnk_Biv", desc = "Minkowski Plane Bivector", bases = {_e12noni, _e13noni, _e23noni, }, key = 1744830464 }
Hyp_Pss = { id = "Hyp_Pss", desc = "Imaginary Sphere Pseudoscalar", bases = {_e123no, _e123ni, }, key = 8421376 }
Hyp_Pnt = { id = "Hyp_Pnt", desc = "Imaginary Sphere Point", bases = {_s, _e1no, _e2no, _e3no, _e1ni, _e2ni, _e3ni, _noni, }, key = 18224641 }
Hyp_Cir = { id = "Hyp_Cir", desc = "Imaginary Sphere Circle", bases = {_e12, _e13, _e23, _e1no, _e2no, _e3no, _e1ni, _e2ni, _e3ni, _e12noni, _e13noni, _e23noni, _e123no, _e123ni, }, key = 1754699368 }
Hyp_Sph = { id = "Hyp_Sph", desc = "Imaginary Sphere Sphere", bases = {_e12no, _e13no, _e23no, _e12ni, _e13ni, _e23ni, _e123, _e123noni, }, key = -2140641152 }
Hyp_Sta = { id = "Hyp_Sta", desc = "Imaginary Sphere Space Time Wedge", bases = {_e1, _e2, _e3, _e12no, _e13no, _e23no, _e12ni, _e13ni, _e23ni, _e1noni, _e2noni, _e3noni, }, key = 375941142 }
Hyp_Vec = { id = "Hyp_Vec", desc = "Imaginary Sphere Vector", bases = {_e1no, _e2no, _e3no, _e1ni, _e2ni, _e3ni, }, key = 1447424 }
Hyp_Biv = { id = "Hyp_Biv", desc = "Imaginary Sphere Bivector", bases = {_e12no, _e13no, _e23no, _e12ni, _e13ni, _e23ni, }, key = 6842368 }
Pss_Sta = { id = "Pss_Sta", desc = "Pseudoscalar Space Time Wedge", bases = {_e12no, _e13no, _e23no, _e12ni, _e13ni, _e23ni, _e1noni, _e2noni, _e3noni, }, key = 375941120 }
Pnt_Lin = { id = "Pnt_Lin", desc = "Point Line", bases = {_e12, _e13, _e23, _e1no, _e2no, _e3no, _e1ni, _e2ni, _e3ni, _noni, _e12noni, _e13noni, _e23noni, _e123ni, }, key = 1771443816 }
Pnt_Dll = { id = "Pnt_Dll", desc = "Point Dual Line", bases = {_e1, _e2, _e3, _ni, _e12no, _e13no, _e23no, _e12ni, _e13ni, _e23ni, _e1noni, _e2noni, _e3noni, _e123, }, key = 376006806 }
Pnt_Vec = { id = "Pnt_Vec", desc = "Point Vector", bases = {_s, _e12, _e13, _e23, _e1no, _e2no, _e3no, _e1ni, _e2ni, _e3ni, }, key = 1447529 }
Pnt_Biv = { id = "Pnt_Biv", desc = "Point Bivector", bases = {_e1, _e2, _e3, _e12no, _e13no, _e23no, _e12ni, _e13ni, _e23ni, _e123, }, key = 6842518 }
Cir_Biv = { id = "Cir_Biv", desc = "Circle Bivector", bases = {_e1, _e2, _e3, _no, _ni, _e12no, _e13no, _e23no, _e12ni, _e13ni, _e23ni, _e1noni, _e2noni, _e3noni, _e123noni, }, key = -1771476714 }
Sph_Vec = { id = "Sph_Vec", desc = "Sphere Vector", bases = {_e12no, _e13no, _e23no, _e12ni, _e13ni, _e23ni, _e1noni, _e2noni, _e3noni, _e123noni, }, key = -1771542528 }
Sph_Biv = { id = "Sph_Biv", desc = "Sphere Bivector", bases = {_e1no, _e2no, _e3no, _e1ni, _e2ni, _e3ni, _noni, _e12noni, _e13noni, _e23noni, }, key = 1763055104 }
Sta_Tri = { id = "Sta_Tri", desc = "Space Time Wedge Trivector", bases = {_e1, _e2, _e3, _e12no, _e13no, _e23no, _e12ni, _e13ni, _e23ni, }, key = 6842390 }
Pln_Pln = { id = "Pln_Pln", desc = "Plane Plane", bases = {_s, _e12, _e13, _e23, _e1ni, _e2ni, _e3ni, }, key = 1441897 }
Pln_Dlp = { id = "Pln_Dlp", desc = "Plane Dual Plane", bases = {_e12ni, _e13ni, _e23ni, _e1noni, _e2noni, _e3noni, _e123noni, }, key = -1771569152 }
Pln_Biv = { id = "Pln_Biv", desc = "Plane Bivector", bases = {_e1ni, _e2ni, _e3ni, _noni, _e12noni, _e13noni, _e23noni, }, key = 1763049472 }
Dlp_Biv = { id = "Dlp_Biv", desc = "Dual Plane Bivector", bases = {_e1, _e2, _e3, _e12ni, _e13ni, _e23ni, _e123, }, key = 6815894 }
Rot_Mnk_Pnt = { id = "Rot_Mnk_Pnt", desc = "Rotor Minkowski Plane Point", bases = {_no, _ni, _e12no, _e13no, _e23no, _e12ni, _e13ni, _e23ni, _e1noni, _e2noni, _e3noni, _e123noni, }, key = -1771476736 }
Rot_Hyp_Pss = { id = "Rot_Hyp_Pss", desc = "Rotor Imaginary Sphere Pseudoscalar", bases = {_e1no, _e2no, _e3no, _e1ni, _e2ni, _e3ni, _e123no, _e123ni, }, key = 9868800 }
Trv_Mnk_Vec = { id = "Trv_Mnk_Vec", desc = "Transversor Minkowski Plane Vector", bases = {_no, _e12no, _e13no, _e23no, _e1noni, _e2noni, _e3noni, }, key = 369125632 }
Trv_Mnk_Biv = { id = "Trv_Mnk_Biv", desc = "Transversor Minkowski Plane Bivector", bases = {_e1no, _e2no, _e3no, _e12noni, _e13noni, _e23noni, _e123no, }, key = 1744868864 }
Mnk_Pnt_Lin = { id = "Mnk_Pnt_Lin", desc = "Minkowski Plane Point Line", bases = {_s, _e12, _e13, _e23, _e1no, _e2no, _e3no, _e1ni, _e2ni, _e3ni, _e12noni, _e13noni, _e23noni, _e123ni, }, key = 1754666601 }
Mnk_Pnt_Dll = { id = "Mnk_Pnt_Dll", desc = "Minkowski Plane Point Dual Line", bases = {_e1, _e2, _e3, _ni, _e12no, _e13no, _e23no, _e12ni, _e13ni, _e23ni, _e1noni, _e2noni, _e3noni, _e123noni, }, key = -1771476970 }
Ori_ip_Par = { id = "Ori_ip_Par", desc = "Origin Point Pair", bases = {_e1, _e2, _e3, _no, }, key = 278 }
Ori_ip_Cir = { id = "Ori_ip_Cir", desc = "Origin Circle", bases = {_e12, _e13, _e23, _e1no, _e2no, _e3no, }, key = 5736 }
Hyp_ip_Sph = { id = "Hyp_ip_Sph", desc = "Imaginary Sphere Sphere", bases = {_e12no, _e13no, _e23no, _e12ni, _e13ni, _e23ni, _e123, }, key = 6842496 }
Biv_ip_Sph = { id = "Biv_ip_Sph", desc = "Bivector Sphere", bases = {_e1no, _e2no, _e3no, _e1ni, _e2ni, _e3ni, _noni, }, key = 18224640 }
Gld_ip_Tnb = { id = "Gld_ip_Tnb", desc = "Glide Tangent Bivector at Origin", bases = {_s, _e12, _e13, _e23, _e1no, _e2no, _e3no, }, key = 5737 }
Gld_ip_Tnt = { id = "Gld_ip_Tnt", desc = "Glide Tangent Trivector at Origin", bases = {_e1, _e2, _e3, _e12no, _e13no, _e23no, _e123, }, key = 26774 }
Ori_op_Par = { id = "Ori_op_Par", desc = "Origin Point Pair", bases = {_e12no, _e13no, _e23no, _e1noni, _e2noni, _e3noni, }, key = 369125376 }
Ori_op_Cir = { id = "Ori_op_Cir", desc = "Origin Circle", bases = {_e12noni, _e13noni, _e23noni, _e123no, }, key = 1744863232 }
Ori_op_Gld = { id = "Ori_op_Gld", desc = "Origin Glide", bases = {_e1no, _e2no, _e3no, _noni, _e12noni, _e13noni, _e23noni, }, key = 1761613312 }
Tnv_op_Gld = { id = "Tnv_op_Gld", desc = "Tangent Vector at Origin Glide", bases = {_e12no, _e13no, _e23no, _e1noni, _e2noni, _e3noni, _e123noni, }, key = -1778358272 }
Mnk_Ori_ip_Par = { id = "Mnk_Ori_ip_Par", desc = "Minkowski Plane Origin Point Pair", bases = {_no, _e1noni, _e2noni, _e3noni, }, key = 369099008 }
Mnk_Ori_ip_Cir = { id = "Mnk_Ori_ip_Cir", desc = "Minkowski Plane Origin Circle", bases = {_e1no, _e2no, _e3no, _e12noni, _e13noni, _e23noni, }, key = 1744836096 }
Mnk_Hyp_ip_Sph = { id = "Mnk_Hyp_ip_Sph", desc = "Minkowski Plane Imaginary Sphere Sphere", bases = {_e12no, _e13no, _e23no, _e12ni, _e13ni, _e23ni, _e123noni, }, key = -2140641280 }
Mnk_Biv_ip_Sph = { id = "Mnk_Biv_ip_Sph", desc = "Minkowski Plane Bivector Sphere", bases = {_s, _e1no, _e2no, _e3no, _e1ni, _e2ni, _e3ni, }, key = 1447425 }
Mnk_Ori_op_Par = { id = "Mnk_Ori_op_Par", desc = "Minkowski Plane Origin Point Pair", bases = {_e1, _e2, _e3, _e12no, _e13no, _e23no, }, key = 26646 }
Mnk_Ori_op_Cir = { id = "Mnk_Ori_op_Cir", desc = "Minkowski Plane Origin Circle", bases = {_e12, _e13, _e23, _e123no, }, key = 32872 }
Pnt_Ori_ip_Cir = { id = "Pnt_Ori_ip_Cir", desc = "Point Origin Circle", bases = {_e1, _e2, _e3, _no, _e12no, _e13no, _e23no, _e12ni, _e13ni, _e23ni, _e1noni, _e2noni, _e3noni, _e123, }, key = 375941526 }
Pnt_Ori_op_Par = { id = "Pnt_Ori_op_Par", desc = "Point Origin Point Pair", bases = {_e12, _e13, _e23, _e1no, _e2no, _e3no, _e1ni, _e2ni, _e3ni, _noni, _e12noni, _e13noni, _e23noni, _e123no, }, key = 1763087976 }
Pnt_Mnk_Ori_ip_Cir = { id = "Pnt_Mnk_Ori_ip_Cir", desc = "Point Minkowski Plane Origin Circle", bases = {_e1, _e2, _e3, _no, _e12no, _e13no, _e23no, _e12ni, _e13ni, _e23ni, _e1noni, _e2noni, _e3noni, _e123noni, }, key = -1771542250 }
Pnt_Mnk_Ori_op_Par = { id = "Pnt_Mnk_Ori_op_Par", desc = "Point Minkowski Plane Origin Point Pair", bases = {_s, _e12, _e13, _e23, _e1no, _e2no, _e3no, _e1ni, _e2ni, _e3ni, _e12noni, _e13noni, _e23noni, _e123no, }, key = 1746310761 }
Vec_Hyp_ip_Sph = { id = "Vec_Hyp_ip_Sph", desc = "Vector Imaginary Sphere Sphere", bases = {_e12, _e13, _e23, _e1no, _e2no, _e3no, _e1ni, _e2ni, _e3ni, _e123no, _e123ni, }, key = 9868904 }
Vec_Biv_ip_Sph = { id = "Vec_Biv_ip_Sph", desc = "Vector Bivector Sphere", bases = {_no, _ni, _e12no, _e13no, _e23no, _e12ni, _e13ni, _e23ni, _e1noni, _e2noni, _e3noni, }, key = 376006912 }
Vec_Mnk_Hyp_ip_Sph = { id = "Vec_Mnk_Hyp_ip_Sph", desc = "Vector Minkowski Plane Imaginary Sphere Sphere", bases = {_e1no, _e2no, _e3no, _e1ni, _e2ni, _e3ni, _e12noni, _e13noni, _e23noni, _e123no, _e123ni, }, key = 1754699264 }
Vec_Mnk_Biv_ip_Sph = { id = "Vec_Mnk_Biv_ip_Sph", desc = "Vector Minkowski Plane Bivector Sphere", bases = {_e1, _e2, _e3, _no, _ni, _e12no, _e13no, _e23no, _e12ni, _e13ni, _e23ni, }, key = 6908182 }
States = {
Sca,
Ori,
Inf,
Mnk,
Hyp,
Pss,
Pnt,
Par,
Cir,
Sph,
Sta,
Drv,
Drb,
Drt,
Tnv,
Tnb,
Tnt,
Lin,
Pln,
Flp,
Dfp,
Dll,
Dlp,
Vec,
Biv,
Tri,
Gld,
}

Pinors = {
Vec,
Dlp,
Pln,
Dll,
Lin,
Pnt,
Par,
Cir,
Sph,
Gld,
}

Versors = {
Rot,
Mot,
Dil,
Trv,
Mtd,
Trs,
Rtc,
Mtt,
Rtt,
Rtd,
Tvd,
Tsd,
Trt,
Rvd,
Tst,
Tvt,
Bst,
}

Intermediates = {
Rot_Ori,
Rot_Inf,
Rot_Mnk,
Rot_Hyp,
Rot_Pss,
Rot_Pnt,
Rot_Sph,
Rot_Sta,
Rot_Drv,
Rot_Tnv,
Rot_Lin,
Rot_Pln,
Rot_Dfp,
Rot_Vec,
Mot_Ori,
Dil_Pss,
Dil_Pnt,
Dil_Cir,
Dil_Sph,
Dil_Sta,
Dil_Lin,
Dil_Pln,
Dil_Dfp,
Dil_Dll,
Dil_Dlp,
Dil_Vec,
Dil_Biv,
Dil_Gld,
Trv_Mnk,
Trv_Pss,
Trv_Pnt,
Trv_Cir,
Trv_Sph,
Trv_Drv,
Trv_Drb,
Trv_Vec,
Trv_Biv,
Trv_Tri,
Mtd_Pss,
Trs_Ori,
Trs_Pss,
Trs_Pnt,
Trs_Cir,
Trs_Sph,
Trs_Tnv,
Trs_Tnb,
Trs_Tnt,
Trs_Lin,
Trs_Pln,
Trs_Dll,
Rtt_Mnk,
Rtt_Pss,
Rtt_Vec,
Rtd_Pss,
Tvd_Pss,
Tvd_Vec,
Tvd_Biv,
Tsd_Pln,
Trt_Hyp,
Bst_Mnk,
Bst_Pss,
Bst_Pnt,
Bst_Sph,
Bst_Biv,
Bst_Tri,
Ori_Ori,
Ori_Sta,
Ori_Lin,
Mnk_Pnt,
Mnk_Par,
Mnk_Cir,
Mnk_Sph,
Mnk_Sta,
Mnk_Lin,
Mnk_Pln,
Mnk_Dll,
Mnk_Dlp,
Mnk_Vec,
Mnk_Biv,
Hyp_Pss,
Hyp_Pnt,
Hyp_Cir,
Hyp_Sph,
Hyp_Sta,
Hyp_Vec,
Hyp_Biv,
Pss_Sta,
Pnt_Lin,
Pnt_Dll,
Pnt_Vec,
Pnt_Biv,
Cir_Biv,
Sph_Vec,
Sph_Biv,
Sta_Tri,
Pln_Pln,
Pln_Dlp,
Pln_Biv,
Dlp_Biv,
Rot_Mnk_Pnt,
Rot_Hyp_Pss,
Trv_Mnk_Vec,
Trv_Mnk_Biv,
Mnk_Pnt_Lin,
Mnk_Pnt_Dll,
Ori_ip_Par,
Ori_ip_Cir,
Hyp_ip_Sph,
Biv_ip_Sph,
Gld_ip_Tnb,
Gld_ip_Tnt,
Ori_op_Par,
Ori_op_Cir,
Ori_op_Gld,
Tnv_op_Gld,
Mnk_Ori_ip_Par,
Mnk_Ori_ip_Cir,
Mnk_Hyp_ip_Sph,
Mnk_Biv_ip_Sph,
Mnk_Ori_op_Par,
Mnk_Ori_op_Cir,
Pnt_Ori_ip_Cir,
Pnt_Ori_op_Par,
Pnt_Mnk_Ori_ip_Cir,
Pnt_Mnk_Ori_op_Par,
Vec_Hyp_ip_Sph,
Vec_Biv_ip_Sph,
Vec_Mnk_Hyp_ip_Sph,
Vec_Mnk_Biv_ip_Sph,
}

AllStates = {
Rot,
Mot,
Dil,
Trv,
Mtd,
Trs,
Rtc,
Mtt,
Rtt,
Rtd,
Tvd,
Tsd,
Trt,
Rvd,
Tst,
Tvt,
Bst,
Sca,
Ori,
Inf,
Mnk,
Hyp,
Pss,
Pnt,
Par,
Cir,
Sph,
Sta,
Drv,
Drb,
Drt,
Tnv,
Tnb,
Tnt,
Lin,
Pln,
Flp,
Dfp,
Dll,
Dlp,
Vec,
Biv,
Tri,
Gld,
Rot_Ori,
Rot_Inf,
Rot_Mnk,
Rot_Hyp,
Rot_Pss,
Rot_Pnt,
Rot_Sph,
Rot_Sta,
Rot_Drv,
Rot_Tnv,
Rot_Lin,
Rot_Pln,
Rot_Dfp,
Rot_Vec,
Mot_Ori,
Dil_Pss,
Dil_Pnt,
Dil_Cir,
Dil_Sph,
Dil_Sta,
Dil_Lin,
Dil_Pln,
Dil_Dfp,
Dil_Dll,
Dil_Dlp,
Dil_Vec,
Dil_Biv,
Dil_Gld,
Trv_Mnk,
Trv_Pss,
Trv_Pnt,
Trv_Cir,
Trv_Sph,
Trv_Drv,
Trv_Drb,
Trv_Vec,
Trv_Biv,
Trv_Tri,
Mtd_Pss,
Trs_Ori,
Trs_Pss,
Trs_Pnt,
Trs_Cir,
Trs_Sph,
Trs_Tnv,
Trs_Tnb,
Trs_Tnt,
Trs_Lin,
Trs_Pln,
Trs_Dll,
Rtt_Mnk,
Rtt_Pss,
Rtt_Vec,
Rtd_Pss,
Tvd_Pss,
Tvd_Vec,
Tvd_Biv,
Tsd_Pln,
Trt_Hyp,
Bst_Mnk,
Bst_Pss,
Bst_Pnt,
Bst_Sph,
Bst_Biv,
Bst_Tri,
Ori_Ori,
Ori_Sta,
Ori_Lin,
Mnk_Pnt,
Mnk_Par,
Mnk_Cir,
Mnk_Sph,
Mnk_Sta,
Mnk_Lin,
Mnk_Pln,
Mnk_Dll,
Mnk_Dlp,
Mnk_Vec,
Mnk_Biv,
Hyp_Pss,
Hyp_Pnt,
Hyp_Cir,
Hyp_Sph,
Hyp_Sta,
Hyp_Vec,
Hyp_Biv,
Pss_Sta,
Pnt_Lin,
Pnt_Dll,
Pnt_Vec,
Pnt_Biv,
Cir_Biv,
Sph_Vec,
Sph_Biv,
Sta_Tri,
Pln_Pln,
Pln_Dlp,
Pln_Biv,
Dlp_Biv,
Rot_Mnk_Pnt,
Rot_Hyp_Pss,
Trv_Mnk_Vec,
Trv_Mnk_Biv,
Mnk_Pnt_Lin,
Mnk_Pnt_Dll,
Ori_ip_Par,
Ori_ip_Cir,
Hyp_ip_Sph,
Biv_ip_Sph,
Gld_ip_Tnb,
Gld_ip_Tnt,
Ori_op_Par,
Ori_op_Cir,
Ori_op_Gld,
Tnv_op_Gld,
Mnk_Ori_ip_Par,
Mnk_Ori_ip_Cir,
Mnk_Hyp_ip_Sph,
Mnk_Biv_ip_Sph,
Mnk_Ori_op_Par,
Mnk_Ori_op_Cir,
Pnt_Ori_ip_Cir,
Pnt_Ori_op_Par,
Pnt_Mnk_Ori_ip_Cir,
Pnt_Mnk_Ori_op_Par,
Vec_Hyp_ip_Sph,
Vec_Biv_ip_Sph,
Vec_Mnk_Hyp_ip_Sph,
Vec_Mnk_Biv_ip_Sph,
}
for i,iv in ipairs(AllStates) do
		iv.idx = i
		for k,kv in ipairs(AllStates) do
			if iv.id ~= kv.id then 
				if iv.key == kv.key then print("keys match!!", iv.id, kv.id) end
			end
		end
	end