
require "basis"
--GENERATED PERMUTATIONS OF CL4,1 ON A NULL BASIS (Selected using a geometrical heuristic)
--total number of built types: 115
--GENERATED BY BUILD.LUA

--total number of all types: 50
Rot = { id = "Rot", desc = "Rotor", bases = {_s, _e12, _e13, _e23, }, key = 105 }
Mot = { id = "Mot", desc = "Motor", bases = {_s, _e12, _e13, _e23, _e1ni, _e2ni, _e3ni, _e123ni, }, key = 9830505 }
Dil = { id = "Dil", desc = "Dilator", bases = {_s, _noni, }, key = 16777217 }
Trv = { id = "Trv", desc = "Transversor", bases = {_s, _e1no, _e2no, _e3no, }, key = 5633 }
Mtd = { id = "Mtd", desc = "Motor Dilator", bases = {_s, _e12, _e13, _e23, _e1ni, _e2ni, _e3ni, _noni, _e12noni, _e13noni, _e23noni, _e123ni, }, key = 1771438185 }
Trs = { id = "Trs", desc = "Translator", bases = {_s, _e1ni, _e2ni, _e3ni, }, key = 1441793 }
Rtc = { id = "Rtc", desc = "Rotor Circle", bases = {_e1, _e2, _e3, _no, _ni, _e12no, _e13no, _e23no, _e12ni, _e13ni, _e23ni, _e1noni, _e2noni, _e3noni, _e123, _e123noni, }, key = -1771476586 }
Mtt = { id = "Mtt", desc = "Motor Transversor", bases = {_s, _e12, _e13, _e23, _e1no, _e2no, _e3no, _e1ni, _e2ni, _e3ni, _noni, _e12noni, _e13noni, _e23noni, _e123no, _e123ni, }, key = 1771476585 }
Rtt = { id = "Rtt", desc = "Rotor Transveror", bases = {_s, _e12, _e13, _e23, _e1no, _e2no, _e3no, _e123no, }, key = 38505 }
Rtd = { id = "Rtd", desc = "Rotor Dilator", bases = {_s, _e12, _e13, _e23, _noni, _e12noni, _e13noni, _e23noni, }, key = 1761607785 }
Tvd = { id = "Tvd", desc = "Transversor Dilator", bases = {_s, _e1no, _e2no, _e3no, _noni, }, key = 16782849 }
Tsd = { id = "Tsd", desc = "Translator Dilator", bases = {_s, _e1ni, _e2ni, _e3ni, _noni, }, key = 18219009 }
Trt = { id = "Trt", desc = "Transversor Translator", bases = {_s, _e12, _e13, _e23, _e1no, _e2no, _e3no, _e1ni, _e2ni, _e3ni, _noni, _e12noni, _e13noni, _e23noni, }, key = 1763055209 }
Rvd = { id = "Rvd", desc = "Rotor Transversor Dilator", bases = {_s, _e12, _e13, _e23, _e1no, _e2no, _e3no, _noni, _e12noni, _e13noni, _e23noni, _e123no, }, key = 1761646185 }
Tst = { id = "Tst", desc = "Transv Transv Transl", bases = {_s, _e12, _e13, _e23, _e1no, _e2no, _e3no, _e1ni, _e2ni, _e3ni, _noni, _e12noni, _e13noni, _e23noni, _e123no, }, key = 1763087977 }
Tvt = { id = "Tvt", desc = "Trans Transv Transl", bases = {_s, _e12, _e13, _e23, _e1no, _e2no, _e3no, _e1ni, _e2ni, _e3ni, _noni, _e12noni, _e13noni, _e23noni, _e123ni, }, key = 1771443817 }
Bst = { id = "Bst", desc = "Booster", bases = {_s, _e12, _e13, _e23, _e1no, _e2no, _e3no, _e1ni, _e2ni, _e3ni, _noni, }, key = 18224745 }
Sca = { id = "Sca", desc = "Scalar", bases = {_s, }, key = 1 }
Ori = { id = "Ori", desc = "Origin", bases = {_no, }, key = 256 }
Inf = { id = "Inf", desc = "Infinity", bases = {_ni, }, key = 65536 }
Mnk = { id = "Mnk", desc = "Minkowski Plane", bases = {_noni, }, key = 16777216 }
Hyp = { id = "Hyp", desc = "Imaginary Sphere", bases = {_no, _ni, }, key = 65792 }
Pss = { id = "Pss", desc = "Pseudoscalar", bases = {_e123noni, }, key = -2147483648 }
Pnt = { id = "Pnt", desc = "Point", bases = {_e1, _e2, _e3, _no, _ni, }, key = 65814 }
Par = { id = "Par", desc = "Point Pair", bases = {_e12, _e13, _e23, _e1no, _e2no, _e3no, _e1ni, _e2ni, _e3ni, _noni, }, key = 18224744 }
Cir = { id = "Cir", desc = "Circle", bases = {_e12no, _e13no, _e23no, _e12ni, _e13ni, _e23ni, _e1noni, _e2noni, _e3noni, _e123, }, key = 375941248 }
Sph = { id = "Sph", desc = "Sphere", bases = {_e12noni, _e13noni, _e23noni, _e123no, _e123ni, }, key = 1753251840 }
Sta = { id = "Sta", desc = "Space Time Wedge", bases = {_e12, _e13, _e23, _e1no, _e2no, _e3no, _e1ni, _e2ni, _e3ni, }, key = 1447528 }
Drv = { id = "Drv", desc = "Direction Vector", bases = {_e1ni, _e2ni, _e3ni, }, key = 1441792 }
Drb = { id = "Drb", desc = "Direction Bivector", bases = {_e12ni, _e13ni, _e23ni, }, key = 6815744 }
Drt = { id = "Drt", desc = "Direction Trivector", bases = {_e123ni, }, key = 8388608 }
Tnv = { id = "Tnv", desc = "Tangent Vector at Origin", bases = {_e1no, _e2no, _e3no, }, key = 5632 }
Tnb = { id = "Tnb", desc = "Tangent Bivector at Origin", bases = {_e12no, _e13no, _e23no, }, key = 26624 }
Tnt = { id = "Tnt", desc = "Tangent Trivector at Origin", bases = {_e123no, }, key = 32768 }
Lin = { id = "Lin", desc = "Line", bases = {_e12ni, _e13ni, _e23ni, _e1noni, _e2noni, _e3noni, }, key = 375914496 }
Pln = { id = "Pln", desc = "Plane", bases = {_e12noni, _e13noni, _e23noni, _e123ni, }, key = 1753219072 }
Flp = { id = "Flp", desc = "Flat Point", bases = {_e1ni, _e2ni, _e3ni, _noni, }, key = 18219008 }
Dfp = { id = "Dfp", desc = "Dual Flat Point", bases = {_e12ni, _e13ni, _e23ni, _e123, }, key = 6815872 }
Dll = { id = "Dll", desc = "Dual Line", bases = {_e12, _e13, _e23, _e1ni, _e2ni, _e3ni, }, key = 1441896 }
Dlp = { id = "Dlp", desc = "Dual Plane", bases = {_e1, _e2, _e3, _ni, }, key = 65558 }
Vec = { id = "Vec", desc = "Vector", bases = {_e1, _e2, _e3, }, key = 22 }
Biv = { id = "Biv", desc = "Bivector", bases = {_e12, _e13, _e23, }, key = 104 }
Tri = { id = "Tri", desc = "Trivector", bases = {_e123, }, key = 128 }
Aff = { id = "Aff", desc = "Affine Point", bases = {_e1, _e2, _e3, _no, }, key = 278 }
Afl = { id = "Afl", desc = "Affine Line", bases = {_e12, _e13, _e23, _e1no, _e2no, _e3no, }, key = 5736 }
Afp = { id = "Afp", desc = "Affine Plane", bases = {_e12no, _e13no, _e23no, _e123, }, key = 26752 }
Dap = { id = "Dap", desc = "Dual Affine Plane", bases = {_e1no, _e2no, _e3no, _noni, }, key = 16782848 }
Daf = { id = "Daf", desc = "Dual Affine Point", bases = {_e12noni, _e13noni, _e23noni, _e123no, }, key = 1744863232 }
Dal = { id = "Dal", desc = "Dual Affine Line", bases = {_e12no, _e13no, _e23no, _e1noni, _e2noni, _e3noni, }, key = 369125376 }
Mnv = { id = "Mnv", desc = "Minkowski Vector", bases = {_e1noni, _e2noni, _e3noni, }, key = 369098752 }
Ori_Ori = { id = "Ori_Ori", desc = "Origin Origin", bases = {}, key = 0 }
Ori_Par = { id = "Ori_Par", desc = "Origin Point Pair", bases = {_e1, _e2, _e3, _no, _e12no, _e13no, _e23no, _e1noni, _e2noni, _e3noni, }, key = 369125654 }
Ori_Cir = { id = "Ori_Cir", desc = "Origin Circle", bases = {_e12, _e13, _e23, _e1no, _e2no, _e3no, _e12noni, _e13noni, _e23noni, _e123no, }, key = 1744868968 }
Ori_Sph = { id = "Ori_Sph", desc = "Origin Sphere", bases = {_e12no, _e13no, _e23no, _e123, _e123noni, }, key = -2147456896 }
Ori_Sta = { id = "Ori_Sta", desc = "Origin Space Time Wedge", bases = {_e1, _e2, _e3, _e12no, _e13no, _e23no, _e1noni, _e2noni, _e3noni, }, key = 369125398 }
Ori_Drv = { id = "Ori_Drv", desc = "Origin Direction Vector", bases = {_e1, _e2, _e3, _e1noni, _e2noni, _e3noni, }, key = 369098774 }
Ori_Drb = { id = "Ori_Drb", desc = "Origin Direction Bivector", bases = {_e12, _e13, _e23, _e12noni, _e13noni, _e23noni, }, key = 1744830568 }
Ori_Drt = { id = "Ori_Drt", desc = "Origin Direction Trivector", bases = {_e123, _e123noni, }, key = -2147483520 }
Ori_Lin = { id = "Ori_Lin", desc = "Origin Line", bases = {_e12, _e13, _e23, _e1no, _e2no, _e3no, _e12noni, _e13noni, _e23noni, }, key = 1744836200 }
Ori_Flp = { id = "Ori_Flp", desc = "Origin Flat Point", bases = {_e1, _e2, _e3, _no, _e1noni, _e2noni, _e3noni, }, key = 369099030 }
Ori_Dfp = { id = "Ori_Dfp", desc = "Origin Dual Flat Point", bases = {_e12, _e13, _e23, _e12noni, _e13noni, _e23noni, _e123no, }, key = 1744863336 }
Inf_Par = { id = "Inf_Par", desc = "Infinity Point Pair", bases = {_e1, _e2, _e3, _ni, _e12ni, _e13ni, _e23ni, _e1noni, _e2noni, _e3noni, }, key = 375980054 }
Inf_Cir = { id = "Inf_Cir", desc = "Infinity Circle", bases = {_e12, _e13, _e23, _e1ni, _e2ni, _e3ni, _e12noni, _e13noni, _e23noni, _e123ni, }, key = 1754660968 }
Inf_Sph = { id = "Inf_Sph", desc = "Infinity Sphere", bases = {_e12ni, _e13ni, _e23ni, _e123, _e123noni, }, key = -2140667776 }
Inf_Sta = { id = "Inf_Sta", desc = "Infinity Space Time Wedge", bases = {_e1, _e2, _e3, _e12ni, _e13ni, _e23ni, _e1noni, _e2noni, _e3noni, }, key = 375914518 }
Inf_Afp = { id = "Inf_Afp", desc = "Infinity Affine Plane", bases = {_e12, _e13, _e23, _e12noni, _e13noni, _e23noni, _e123ni, }, key = 1753219176 }
Inf_Dap = { id = "Inf_Dap", desc = "Infinity Dual Affine Plane", bases = {_e1, _e2, _e3, _ni, _e1noni, _e2noni, _e3noni, }, key = 369164310 }
Inf_Dal = { id = "Inf_Dal", desc = "Infinity Dual Affine Line", bases = {_e12, _e13, _e23, _e1ni, _e2ni, _e3ni, _e12noni, _e13noni, _e23noni, }, key = 1746272360 }
Mnk_Pnt = { id = "Mnk_Pnt", desc = "Minkowski Plane Point", bases = {_no, _ni, _e1noni, _e2noni, _e3noni, }, key = 369164544 }
Mnk_Par = { id = "Mnk_Par", desc = "Minkowski Plane Point Pair", bases = {_s, _e1no, _e2no, _e3no, _e1ni, _e2ni, _e3ni, _e12noni, _e13noni, _e23noni, }, key = 1746277889 }
Mnk_Cir = { id = "Mnk_Cir", desc = "Minkowski Plane Circle", bases = {_e1, _e2, _e3, _e12no, _e13no, _e23no, _e12ni, _e13ni, _e23ni, _e123noni, }, key = -2140641258 }
Mnk_Sph = { id = "Mnk_Sph", desc = "Minkowski Plane Sphere", bases = {_e12, _e13, _e23, _e123no, _e123ni, }, key = 8421480 }
Mnk_Sta = { id = "Mnk_Sta", desc = "Minkowski Plane Space Time Wedge", bases = {_e1no, _e2no, _e3no, _e1ni, _e2ni, _e3ni, _e12noni, _e13noni, _e23noni, }, key = 1746277888 }
Mnk_Lin = { id = "Mnk_Lin", desc = "Minkowski Plane Line", bases = {_e1, _e2, _e3, _e12ni, _e13ni, _e23ni, }, key = 6815766 }
Mnk_Pln = { id = "Mnk_Pln", desc = "Minkowski Plane Plane", bases = {_e12, _e13, _e23, _e123ni, }, key = 8388712 }
Mnk_Dfp = { id = "Mnk_Dfp", desc = "Minkowski Plane Dual Flat Point", bases = {_e12ni, _e13ni, _e23ni, _e123noni, }, key = -2140667904 }
Mnk_Dll = { id = "Mnk_Dll", desc = "Minkowski Plane Dual Line", bases = {_e1ni, _e2ni, _e3ni, _e12noni, _e13noni, _e23noni, }, key = 1746272256 }
Mnk_Dlp = { id = "Mnk_Dlp", desc = "Minkowski Plane Dual Plane", bases = {_ni, _e1noni, _e2noni, _e3noni, }, key = 369164288 }
Mnk_Biv = { id = "Mnk_Biv", desc = "Minkowski Plane Bivector", bases = {_e12noni, _e13noni, _e23noni, }, key = 1744830464 }
Mnk_Aff = { id = "Mnk_Aff", desc = "Minkowski Plane Affine Point", bases = {_no, _e1noni, _e2noni, _e3noni, }, key = 369099008 }
Mnk_Afl = { id = "Mnk_Afl", desc = "Minkowski Plane Affine Line", bases = {_e1no, _e2no, _e3no, _e12noni, _e13noni, _e23noni, }, key = 1744836096 }
Mnk_Afp = { id = "Mnk_Afp", desc = "Minkowski Plane Affine Plane", bases = {_e12no, _e13no, _e23no, _e123noni, }, key = -2147457024 }
Mnk_Daf = { id = "Mnk_Daf", desc = "Minkowski Plane Dual Affine Point", bases = {_e12, _e13, _e23, _e123no, }, key = 32872 }
Mnk_Dal = { id = "Mnk_Dal", desc = "Minkowski Plane Dual Affine Line", bases = {_e1, _e2, _e3, _e12no, _e13no, _e23no, }, key = 26646 }
Hyp_Pss = { id = "Hyp_Pss", desc = "Imaginary Sphere Pseudoscalar", bases = {_e123no, _e123ni, }, key = 8421376 }
Hyp_Pnt = { id = "Hyp_Pnt", desc = "Imaginary Sphere Point", bases = {_s, _e1no, _e2no, _e3no, _e1ni, _e2ni, _e3ni, _noni, }, key = 18224641 }
Hyp_Par = { id = "Hyp_Par", desc = "Imaginary Sphere Point Pair", bases = {_e1, _e2, _e3, _no, _ni, _e12no, _e13no, _e23no, _e12ni, _e13ni, _e23ni, _e1noni, _e2noni, _e3noni, }, key = 376006934 }
Hyp_Cir = { id = "Hyp_Cir", desc = "Imaginary Sphere Circle", bases = {_e12, _e13, _e23, _e1no, _e2no, _e3no, _e1ni, _e2ni, _e3ni, _e12noni, _e13noni, _e23noni, _e123no, _e123ni, }, key = 1754699368 }
Hyp_Sph = { id = "Hyp_Sph", desc = "Imaginary Sphere Sphere", bases = {_e12no, _e13no, _e23no, _e12ni, _e13ni, _e23ni, _e123, _e123noni, }, key = -2140641152 }
Hyp_Sta = { id = "Hyp_Sta", desc = "Imaginary Sphere Space Time Wedge", bases = {_e1, _e2, _e3, _e12no, _e13no, _e23no, _e12ni, _e13ni, _e23ni, _e1noni, _e2noni, _e3noni, }, key = 375941142 }
Hyp_Lin = { id = "Hyp_Lin", desc = "Imaginary Sphere Line", bases = {_e12, _e13, _e23, _e1no, _e2no, _e3no, _e1ni, _e2ni, _e3ni, _e12noni, _e13noni, _e23noni, }, key = 1746277992 }
Hyp_Flp = { id = "Hyp_Flp", desc = "Imaginary Sphere Flat Point", bases = {_e1, _e2, _e3, _no, _ni, _e1noni, _e2noni, _e3noni, }, key = 369164566 }
Hyp_Dfp = { id = "Hyp_Dfp", desc = "Imaginary Sphere Dual Flat Point", bases = {_e12, _e13, _e23, _e12noni, _e13noni, _e23noni, _e123no, _e123ni, }, key = 1753251944 }
Hyp_Vec = { id = "Hyp_Vec", desc = "Imaginary Sphere Vector", bases = {_e1no, _e2no, _e3no, _e1ni, _e2ni, _e3ni, }, key = 1447424 }
Hyp_Biv = { id = "Hyp_Biv", desc = "Imaginary Sphere Bivector", bases = {_e12no, _e13no, _e23no, _e12ni, _e13ni, _e23ni, }, key = 6842368 }
Pss_Sta = { id = "Pss_Sta", desc = "Pseudoscalar Space Time Wedge", bases = {_e12no, _e13no, _e23no, _e12ni, _e13ni, _e23ni, _e1noni, _e2noni, _e3noni, }, key = 375941120 }
Pnt_Par = { id = "Pnt_Par", desc = "Point Point Pair", bases = {_e1, _e2, _e3, _no, _ni, _e12no, _e13no, _e23no, _e12ni, _e13ni, _e23ni, _e1noni, _e2noni, _e3noni, _e123, }, key = 376007062 }
Pnt_Cir = { id = "Pnt_Cir", desc = "Point Circle", bases = {_e12, _e13, _e23, _e1no, _e2no, _e3no, _e1ni, _e2ni, _e3ni, _noni, _e12noni, _e13noni, _e23noni, _e123no, _e123ni, }, key = 1771476584 }
Pnt_Sph = { id = "Pnt_Sph", desc = "Point Sphere", bases = {_e12no, _e13no, _e23no, _e12ni, _e13ni, _e23ni, _e1noni, _e2noni, _e3noni, _e123, _e123noni, }, key = -1771542400 }
Pnt_Lin = { id = "Pnt_Lin", desc = "Point Line", bases = {_e12, _e13, _e23, _e1no, _e2no, _e3no, _e1ni, _e2ni, _e3ni, _noni, _e12noni, _e13noni, _e23noni, _e123ni, }, key = 1771443816 }
Pnt_Flp = { id = "Pnt_Flp", desc = "Point Flat Point", bases = {_e1, _e2, _e3, _no, _ni, _e12ni, _e13ni, _e23ni, _e1noni, _e2noni, _e3noni, }, key = 375980310 }
Pnt_Dfp = { id = "Pnt_Dfp", desc = "Point Dual Flat Point", bases = {_e12, _e13, _e23, _e1ni, _e2ni, _e3ni, _e12noni, _e13noni, _e23noni, _e123no, _e123ni, }, key = 1754693736 }
Pnt_Dll = { id = "Pnt_Dll", desc = "Point Dual Line", bases = {_e1, _e2, _e3, _ni, _e12no, _e13no, _e23no, _e12ni, _e13ni, _e23ni, _e1noni, _e2noni, _e3noni, _e123, }, key = 376006806 }
Pnt_Vec = { id = "Pnt_Vec", desc = "Point Vector", bases = {_s, _e12, _e13, _e23, _e1no, _e2no, _e3no, _e1ni, _e2ni, _e3ni, }, key = 1447529 }
Pnt_Biv = { id = "Pnt_Biv", desc = "Point Bivector", bases = {_e1, _e2, _e3, _e12no, _e13no, _e23no, _e12ni, _e13ni, _e23ni, _e123, }, key = 6842518 }
Pnt_Afl = { id = "Pnt_Afl", desc = "Point Affine Line", bases = {_e1, _e2, _e3, _no, _e12no, _e13no, _e23no, _e12ni, _e13ni, _e23ni, _e1noni, _e2noni, _e3noni, _e123, }, key = 375941526 }
Pnt_Afp = { id = "Pnt_Afp", desc = "Point Affine Plane", bases = {_e12, _e13, _e23, _e1no, _e2no, _e3no, _e12noni, _e13noni, _e23noni, _e123no, _e123ni, }, key = 1753257576 }
Pnt_Dap = { id = "Pnt_Dap", desc = "Point Dual Affine Plane", bases = {_e1, _e2, _e3, _no, _ni, _e12no, _e13no, _e23no, _e1noni, _e2noni, _e3noni, }, key = 369191190 }
Pnt_Dal = { id = "Pnt_Dal", desc = "Point Dual Affine Line", bases = {_e12, _e13, _e23, _e1no, _e2no, _e3no, _e1ni, _e2ni, _e3ni, _noni, _e12noni, _e13noni, _e23noni, _e123no, }, key = 1763087976 }
Pnt_Mnv = { id = "Pnt_Mnv", desc = "Point Minkowski Vector", bases = {_e1no, _e2no, _e3no, _e1ni, _e2ni, _e3ni, _noni, _e12noni, _e13noni, _e23noni, }, key = 1763055104 }
Par_Drb = { id = "Par_Drb", desc = "Point Pair Direction Bivector", bases = {_e1, _e2, _e3, _ni, _e12ni, _e13ni, _e23ni, _e1noni, _e2noni, _e3noni, _e123, _e123noni, }, key = -1771503466 }
Par_Tnb = { id = "Par_Tnb", desc = "Point Pair Tangent Bivector at Origin", bases = {_e1, _e2, _e3, _no, _e12no, _e13no, _e23no, _e1noni, _e2noni, _e3noni, _e123, _e123noni, }, key = -1778357866 }
Par_Dfp = { id = "Par_Dfp", desc = "Point Pair Dual Flat Point", bases = {_e1, _e2, _e3, _ni, _e12no, _e13no, _e23no, _e12ni, _e13ni, _e23ni, _e1noni, _e2noni, _e3noni, _e123, _e123noni, }, key = -1771476842 }
Par_Biv = { id = "Par_Biv", desc = "Point Pair Bivector", bases = {_s, _e12, _e13, _e23, _e1no, _e2no, _e3no, _e1ni, _e2ni, _e3ni, _e12noni, _e13noni, _e23noni, _e123no, _e123ni, }, key = 1754699369 }
Par_Afp = { id = "Par_Afp", desc = "Point Pair Affine Plane", bases = {_e1, _e2, _e3, _no, _e12no, _e13no, _e23no, _e12ni, _e13ni, _e23ni, _e1noni, _e2noni, _e3noni, _e123, _e123noni, }, key = -1771542122 }
Par_Mnv = { id = "Par_Mnv", desc = "Point Pair Minkowski Vector", bases = {_e1, _e2, _e3, _no, _ni, _e12no, _e13no, _e23no, _e12ni, _e13ni, _e23ni, _e1noni, _e2noni, _e3noni, _e123noni, }, key = -1771476714 }
Sph_Vec = { id = "Sph_Vec", desc = "Sphere Vector", bases = {_e12no, _e13no, _e23no, _e12ni, _e13ni, _e23ni, _e1noni, _e2noni, _e3noni, _e123noni, }, key = -1771542528 }
Sta_Vec = { id = "Sta_Vec", desc = "Space Time Wedge Vector", bases = {_e1, _e2, _e3, _no, _ni, _e12no, _e13no, _e23no, _e12ni, _e13ni, _e23ni, _e123, }, key = 6908310 }
Sta_Biv = { id = "Sta_Biv", desc = "Space Time Wedge Bivector", bases = {_s, _e12, _e13, _e23, _e1no, _e2no, _e3no, _e1ni, _e2ni, _e3ni, _e123no, _e123ni, }, key = 9868905 }
Sta_Tri = { id = "Sta_Tri", desc = "Space Time Wedge Trivector", bases = {_e1, _e2, _e3, _e12no, _e13no, _e23no, _e12ni, _e13ni, _e23ni, }, key = 6842390 }
Sta_Mnv = { id = "Sta_Mnv", desc = "Space Time Wedge Minkowski Vector", bases = {_no, _ni, _e12no, _e13no, _e23no, _e12ni, _e13ni, _e23ni, _e1noni, _e2noni, _e3noni, _e123noni, }, key = -1771476736 }
Drv_Tnb = { id = "Drv_Tnb", desc = "Direction Vector Tangent Bivector at Origin", bases = {_e1, _e2, _e3, _e1noni, _e2noni, _e3noni, _e123, _e123noni, }, key = -1778384746 }
Drv_Lin = { id = "Drv_Lin", desc = "Direction Vector Line", bases = {_ni, _e12ni, _e13ni, _e23ni, }, key = 6881280 }
Drv_Pln = { id = "Drv_Pln", desc = "Direction Vector Plane", bases = {_e1ni, _e2ni, _e3ni, _e123ni, }, key = 9830400 }
Drv_Afp = { id = "Drv_Afp", desc = "Direction Vector Affine Plane", bases = {_e1, _e2, _e3, _e12ni, _e13ni, _e23ni, _e1noni, _e2noni, _e3noni, _e123, _e123noni, }, key = -1771569002 }
Drv_Dap = { id = "Drv_Dap", desc = "Direction Vector Dual Affine Plane", bases = {_s, _e12, _e13, _e23, _e1ni, _e2ni, _e3ni, _noni, _e12noni, _e13noni, _e23noni, }, key = 1763049577 }
Tnv_Flp = { id = "Tnv_Flp", desc = "Tangent Vector at Origin Flat Point", bases = {_s, _e12, _e13, _e23, _e1no, _e2no, _e3no, _noni, _e12noni, _e13noni, _e23noni, }, key = 1761613417 }
Tnv_Dfp = { id = "Tnv_Dfp", desc = "Tangent Vector at Origin Dual Flat Point", bases = {_e1, _e2, _e3, _e12no, _e13no, _e23no, _e1noni, _e2noni, _e3noni, _e123, _e123noni, }, key = -1778358122 }
Tnv_Vec = { id = "Tnv_Vec", desc = "Tangent Vector at Origin Vector", bases = {_no, _e12no, _e13no, _e23no, }, key = 26880 }
Tnv_Biv = { id = "Tnv_Biv", desc = "Tangent Vector at Origin Bivector", bases = {_e1no, _e2no, _e3no, _e123no, }, key = 38400 }
Lin_Pln = { id = "Lin_Pln", desc = "Line Plane", bases = {_e1, _e2, _e3, _ni, _e12ni, _e13ni, _e23ni, _e123, }, key = 6881430 }
Lin_Flp = { id = "Lin_Flp", desc = "Line Flat Point", bases = {_e1, _e2, _e3, _ni, _e12ni, _e13ni, _e23ni, }, key = 6881302 }
Lin_Dfp = { id = "Lin_Dfp", desc = "Line Dual Flat Point", bases = {_e1ni, _e2ni, _e3ni, _e12noni, _e13noni, _e23noni, _e123ni, }, key = 1754660864 }
Lin_Dll = { id = "Lin_Dll", desc = "Line Dual Line", bases = {_ni, _e12ni, _e13ni, _e23ni, _e1noni, _e2noni, _e3noni, _e123noni, }, key = -1771503616 }
Lin_Dlp = { id = "Lin_Dlp", desc = "Line Dual Plane", bases = {_e1ni, _e2ni, _e3ni, _noni, _e12noni, _e13noni, _e23noni, _e123ni, }, key = 1771438080 }
Pln_Pln = { id = "Pln_Pln", desc = "Plane Plane", bases = {_s, _e12, _e13, _e23, _e1ni, _e2ni, _e3ni, }, key = 1441897 }
Pln_Flp = { id = "Pln_Flp", desc = "Plane Flat Point", bases = {_e12, _e13, _e23, _e1ni, _e2ni, _e3ni, _e123ni, }, key = 9830504 }
Pln_Dfp = { id = "Pln_Dfp", desc = "Plane Dual Flat Point", bases = {_ni, _e12ni, _e13ni, _e23ni, _e1noni, _e2noni, _e3noni, }, key = 375980032 }
Pln_Dlp = { id = "Pln_Dlp", desc = "Plane Dual Plane", bases = {_e12ni, _e13ni, _e23ni, _e1noni, _e2noni, _e3noni, _e123noni, }, key = -1771569152 }
Pln_Biv = { id = "Pln_Biv", desc = "Plane Bivector", bases = {_e1ni, _e2ni, _e3ni, _noni, _e12noni, _e13noni, _e23noni, }, key = 1763049472 }
Pln_Mnv = { id = "Pln_Mnv", desc = "Plane Minkowski Vector", bases = {_e1, _e2, _e3, _e12ni, _e13ni, _e23ni, _e123, }, key = 6815894 }
Flp_Afp = { id = "Flp_Afp", desc = "Flat Point Affine Plane", bases = {_e1, _e2, _e3, _e12no, _e13no, _e23no, _e12ni, _e13ni, _e23ni, _e1noni, _e2noni, _e3noni, _e123, _e123noni, }, key = -1771542378 }
Vec_Biv = { id = "Vec_Biv", desc = "Vector Bivector", bases = {_e1, _e2, _e3, _e123, }, key = 150 }
Vec_Aff = { id = "Vec_Aff", desc = "Vector Affine Point", bases = {_s, _e12, _e13, _e23, _e1no, _e2no, _e3no, }, key = 5737 }
Vec_Afl = { id = "Vec_Afl", desc = "Vector Affine Line", bases = {_e1, _e2, _e3, _no, _e12no, _e13no, _e23no, _e123, }, key = 27030 }
Vec_Afp = { id = "Vec_Afp", desc = "Vector Affine Plane", bases = {_e12, _e13, _e23, _e1no, _e2no, _e3no, _e123no, }, key = 38504 }
Vec_Dap = { id = "Vec_Dap", desc = "Vector Dual Affine Plane", bases = {_no, _e12no, _e13no, _e23no, _e1noni, _e2noni, _e3noni, }, key = 369125632 }
Vec_Daf = { id = "Vec_Daf", desc = "Vector Dual Affine Point", bases = {_e12no, _e13no, _e23no, _e1noni, _e2noni, _e3noni, _e123noni, }, key = -1778358272 }
Vec_Dal = { id = "Vec_Dal", desc = "Vector Dual Affine Line", bases = {_e1no, _e2no, _e3no, _noni, _e12noni, _e13noni, _e23noni, _e123no, }, key = 1761646080 }
Vec_Mnv = { id = "Vec_Mnv", desc = "Vector Minkowski Vector", bases = {_noni, _e12noni, _e13noni, _e23noni, }, key = 1761607680 }
Biv_Aff = { id = "Biv_Aff", desc = "Bivector Affine Point", bases = {_e1, _e2, _e3, _e12no, _e13no, _e23no, _e123, }, key = 26774 }
Biv_Afp = { id = "Biv_Afp", desc = "Bivector Affine Plane", bases = {_e1, _e2, _e3, _no, _e12no, _e13no, _e23no, }, key = 26902 }
Biv_Dap = { id = "Biv_Dap", desc = "Bivector Dual Affine Plane", bases = {_e1no, _e2no, _e3no, _e12noni, _e13noni, _e23noni, _e123no, }, key = 1744868864 }
Biv_Daf = { id = "Biv_Daf", desc = "Bivector Dual Affine Point", bases = {_e1no, _e2no, _e3no, _noni, _e12noni, _e13noni, _e23noni, }, key = 1761613312 }
Biv_Dal = { id = "Biv_Dal", desc = "Bivector Dual Affine Line", bases = {_no, _e12no, _e13no, _e23no, _e1noni, _e2noni, _e3noni, _e123noni, }, key = -1778358016 }
Biv_Mnv = { id = "Biv_Mnv", desc = "Bivector Minkowski Vector", bases = {_e1noni, _e2noni, _e3noni, _e123noni, }, key = -1778384896 }
Mnk_Pnt_Sph = { id = "Mnk_Pnt_Sph", desc = "Minkowski Plane Point Sphere", bases = {_e1, _e2, _e3, _e12no, _e13no, _e23no, _e12ni, _e13ni, _e23ni, _e123, _e123noni, }, key = -2140641130 }
Mnk_Pnt_Lin = { id = "Mnk_Pnt_Lin", desc = "Minkowski Plane Point Line", bases = {_s, _e12, _e13, _e23, _e1no, _e2no, _e3no, _e1ni, _e2ni, _e3ni, _e12noni, _e13noni, _e23noni, _e123ni, }, key = 1754666601 }
Mnk_Pnt_Dll = { id = "Mnk_Pnt_Dll", desc = "Minkowski Plane Point Dual Line", bases = {_e1, _e2, _e3, _ni, _e12no, _e13no, _e23no, _e12ni, _e13ni, _e23ni, _e1noni, _e2noni, _e3noni, _e123noni, }, key = -1771476970 }
Mnk_Pnt_Afl = { id = "Mnk_Pnt_Afl", desc = "Minkowski Plane Point Affine Line", bases = {_e1, _e2, _e3, _no, _e12no, _e13no, _e23no, _e12ni, _e13ni, _e23ni, _e1noni, _e2noni, _e3noni, _e123noni, }, key = -1771542250 }
Mnk_Pnt_Dal = { id = "Mnk_Pnt_Dal", desc = "Minkowski Plane Point Dual Affine Line", bases = {_s, _e12, _e13, _e23, _e1no, _e2no, _e3no, _e1ni, _e2ni, _e3ni, _e12noni, _e13noni, _e23noni, _e123no, }, key = 1746310761 }
Mnk_Sta_Biv = { id = "Mnk_Sta_Biv", desc = "Minkowski Plane Space Time Wedge Bivector", bases = {_e1no, _e2no, _e3no, _e1ni, _e2ni, _e3ni, _noni, _e12noni, _e13noni, _e23noni, _e123no, _e123ni, }, key = 1771476480 }
Hyp_Drv_Tnb = { id = "Hyp_Drv_Tnb", desc = "Imaginary Sphere Direction Vector Tangent Bivector at Origin", bases = {_e1no, _e2no, _e3no, _e1ni, _e2ni, _e3ni, _e123no, _e123ni, }, key = 9868800 }
Hyp_Vec_Mnv = { id = "Hyp_Vec_Mnv", desc = "Imaginary Sphere Vector Minkowski Vector", bases = {_no, _ni, _e12no, _e13no, _e23no, _e12ni, _e13ni, _e23ni, }, key = 6908160 }
Pss_Mnk_Pnt_Sph = { id = "Pss_Mnk_Pnt_Sph", desc = "Pseudoscalar Minkowski Plane Point Sphere", bases = {_s, _e1no, _e2no, _e3no, _e1ni, _e2ni, _e3ni, _noni, _e12noni, _e13noni, _e23noni, }, key = 1763055105 }
States = {
Sca,
Ori,
Inf,
Mnk,
Hyp,
Pss,
Pnt,
Par,
Cir,
Sph,
Sta,
Drv,
Drb,
Drt,
Tnv,
Tnb,
Tnt,
Lin,
Pln,
Flp,
Dfp,
Dll,
Dlp,
Vec,
Biv,
Tri,
Aff,
Afl,
Afp,
Dap,
Daf,
Dal,
Mnv,
}

Pinors = {
Vec,
Dlp,
Pln,
Dll,
Lin,
Pnt,
Par,
Cir,
Sph,
}

Versors = {
Rot,
Mot,
Dil,
Trv,
Mtd,
Trs,
Rtc,
Mtt,
Rtt,
Rtd,
Tvd,
Tsd,
Trt,
Rvd,
Tst,
Tvt,
Bst,
}

Intermediates = {
Ori_Ori,
Ori_Par,
Ori_Cir,
Ori_Sph,
Ori_Sta,
Ori_Drv,
Ori_Drb,
Ori_Drt,
Ori_Lin,
Ori_Flp,
Ori_Dfp,
Inf_Par,
Inf_Cir,
Inf_Sph,
Inf_Sta,
Inf_Afp,
Inf_Dap,
Inf_Dal,
Mnk_Pnt,
Mnk_Par,
Mnk_Cir,
Mnk_Sph,
Mnk_Sta,
Mnk_Lin,
Mnk_Pln,
Mnk_Dfp,
Mnk_Dll,
Mnk_Dlp,
Mnk_Biv,
Mnk_Aff,
Mnk_Afl,
Mnk_Afp,
Mnk_Daf,
Mnk_Dal,
Hyp_Pss,
Hyp_Pnt,
Hyp_Par,
Hyp_Cir,
Hyp_Sph,
Hyp_Sta,
Hyp_Lin,
Hyp_Flp,
Hyp_Dfp,
Hyp_Vec,
Hyp_Biv,
Pss_Sta,
Pnt_Par,
Pnt_Cir,
Pnt_Sph,
Pnt_Lin,
Pnt_Flp,
Pnt_Dfp,
Pnt_Dll,
Pnt_Vec,
Pnt_Biv,
Pnt_Afl,
Pnt_Afp,
Pnt_Dap,
Pnt_Dal,
Pnt_Mnv,
Par_Drb,
Par_Tnb,
Par_Dfp,
Par_Biv,
Par_Afp,
Par_Mnv,
Sph_Vec,
Sta_Vec,
Sta_Biv,
Sta_Tri,
Sta_Mnv,
Drv_Tnb,
Drv_Lin,
Drv_Pln,
Drv_Afp,
Drv_Dap,
Tnv_Flp,
Tnv_Dfp,
Tnv_Vec,
Tnv_Biv,
Lin_Pln,
Lin_Flp,
Lin_Dfp,
Lin_Dll,
Lin_Dlp,
Pln_Pln,
Pln_Flp,
Pln_Dfp,
Pln_Dlp,
Pln_Biv,
Pln_Mnv,
Flp_Afp,
Vec_Biv,
Vec_Aff,
Vec_Afl,
Vec_Afp,
Vec_Dap,
Vec_Daf,
Vec_Dal,
Vec_Mnv,
Biv_Aff,
Biv_Afp,
Biv_Dap,
Biv_Daf,
Biv_Dal,
Biv_Mnv,
Mnk_Pnt_Sph,
Mnk_Pnt_Lin,
Mnk_Pnt_Dll,
Mnk_Pnt_Afl,
Mnk_Pnt_Dal,
Mnk_Sta_Biv,
Hyp_Drv_Tnb,
Hyp_Vec_Mnv,
Pss_Mnk_Pnt_Sph,
}

AllStates = {
Rot,
Mot,
Dil,
Trv,
Mtd,
Trs,
Rtc,
Mtt,
Rtt,
Rtd,
Tvd,
Tsd,
Trt,
Rvd,
Tst,
Tvt,
Bst,
Sca,
Ori,
Inf,
Mnk,
Hyp,
Pss,
Pnt,
Par,
Cir,
Sph,
Sta,
Drv,
Drb,
Drt,
Tnv,
Tnb,
Tnt,
Lin,
Pln,
Flp,
Dfp,
Dll,
Dlp,
Vec,
Biv,
Tri,
Aff,
Afl,
Afp,
Dap,
Daf,
Dal,
Mnv,
Ori_Ori,
Ori_Par,
Ori_Cir,
Ori_Sph,
Ori_Sta,
Ori_Drv,
Ori_Drb,
Ori_Drt,
Ori_Lin,
Ori_Flp,
Ori_Dfp,
Inf_Par,
Inf_Cir,
Inf_Sph,
Inf_Sta,
Inf_Afp,
Inf_Dap,
Inf_Dal,
Mnk_Pnt,
Mnk_Par,
Mnk_Cir,
Mnk_Sph,
Mnk_Sta,
Mnk_Lin,
Mnk_Pln,
Mnk_Dfp,
Mnk_Dll,
Mnk_Dlp,
Mnk_Biv,
Mnk_Aff,
Mnk_Afl,
Mnk_Afp,
Mnk_Daf,
Mnk_Dal,
Hyp_Pss,
Hyp_Pnt,
Hyp_Par,
Hyp_Cir,
Hyp_Sph,
Hyp_Sta,
Hyp_Lin,
Hyp_Flp,
Hyp_Dfp,
Hyp_Vec,
Hyp_Biv,
Pss_Sta,
Pnt_Par,
Pnt_Cir,
Pnt_Sph,
Pnt_Lin,
Pnt_Flp,
Pnt_Dfp,
Pnt_Dll,
Pnt_Vec,
Pnt_Biv,
Pnt_Afl,
Pnt_Afp,
Pnt_Dap,
Pnt_Dal,
Pnt_Mnv,
Par_Drb,
Par_Tnb,
Par_Dfp,
Par_Biv,
Par_Afp,
Par_Mnv,
Sph_Vec,
Sta_Vec,
Sta_Biv,
Sta_Tri,
Sta_Mnv,
Drv_Tnb,
Drv_Lin,
Drv_Pln,
Drv_Afp,
Drv_Dap,
Tnv_Flp,
Tnv_Dfp,
Tnv_Vec,
Tnv_Biv,
Lin_Pln,
Lin_Flp,
Lin_Dfp,
Lin_Dll,
Lin_Dlp,
Pln_Pln,
Pln_Flp,
Pln_Dfp,
Pln_Dlp,
Pln_Biv,
Pln_Mnv,
Flp_Afp,
Vec_Biv,
Vec_Aff,
Vec_Afl,
Vec_Afp,
Vec_Dap,
Vec_Daf,
Vec_Dal,
Vec_Mnv,
Biv_Aff,
Biv_Afp,
Biv_Dap,
Biv_Daf,
Biv_Dal,
Biv_Mnv,
Mnk_Pnt_Sph,
Mnk_Pnt_Lin,
Mnk_Pnt_Dll,
Mnk_Pnt_Afl,
Mnk_Pnt_Dal,
Mnk_Sta_Biv,
Hyp_Drv_Tnb,
Hyp_Vec_Mnv,
Pss_Mnk_Pnt_Sph,
}
for i,iv in ipairs(AllStates) do
		iv.idx = i
		for k,kv in ipairs(AllStates) do
			if iv.id ~= kv.id then 
				if iv.key == kv.key then print("keys match!!", iv.id, kv.id) end
			end
		end
	end